"""Tests for litscribe.exporters.bibtex (v2)."""
import pytest


def test_escape_bibtex():
    from litscribe.exporters.bibtex import escape_bibtex
    assert r"\&" in escape_bibtex("A & B")


def test_escape_bibtex_percent():
    from litscribe.exporters.bibtex import escape_bibtex
    assert r"\%" in escape_bibtex("100% correct")


def test_escape_bibtex_empty():
    from litscribe.exporters.bibtex import escape_bibtex
    assert escape_bibtex("") == ""


def test_papers_to_bibtex():
    from litscribe.exporters.bibtex import papers_to_bibtex
    from litscribe.models.paper import Paper
    papers = [
        Paper(
            paper_id="x",
            title="Test Paper",
            authors=["Smith J", "Jones A"],
            abstract="abs",
            year=2024,
            sources={"arxiv": "1"},
            venue="NeurIPS",
        )
    ]
    bib = papers_to_bibtex(papers)
    assert "@" in bib
    assert "Test Paper" in bib
    assert "2024" in bib


def test_papers_to_bibtex_empty():
    from litscribe.exporters.bibtex import papers_to_bibtex
    bib = papers_to_bibtex([])
    assert "% BibTeX bibliography generated by LitScribe" in bib
    assert "0 entries" in bib


def test_papers_to_bibtex_unique_keys():
    from litscribe.exporters.bibtex import papers_to_bibtex
    from litscribe.models.paper import Paper
    paper = Paper(
        paper_id="x1",
        title="Same Title",
        authors=["Smith J"],
        abstract="abs",
        year=2024,
        sources={},
        venue="",
    )
    papers = [paper, paper]
    bib = papers_to_bibtex(papers)
    # Should not raise and both entries should appear
    assert bib.count("@") == 2


def test_generate_cite_key():
    from litscribe.exporters.bibtex import generate_cite_key
    key = generate_cite_key(["Smith J"], 2024, "A Great Paper")
    assert "smith" in key.lower()
    assert "2024" in key


def test_generate_cite_key_no_authors():
    from litscribe.exporters.bibtex import generate_cite_key
    key = generate_cite_key([], 2023, "Unknown Work")
    assert "2023" in key


def test_detect_entry_type_conference():
    from litscribe.exporters.bibtex import detect_entry_type
    assert detect_entry_type("NeurIPS 2023 Conference") == "inproceedings"
    assert detect_entry_type("ICML Proceedings") == "inproceedings"


def test_detect_entry_type_journal():
    from litscribe.exporters.bibtex import detect_entry_type
    assert detect_entry_type("Nature Journal") == "article"
    assert detect_entry_type("IEEE Transactions on Neural Networks") == "article"


def test_detect_entry_type_misc():
    from litscribe.exporters.bibtex import detect_entry_type
    assert detect_entry_type("arXiv preprint") == "misc"
    assert detect_entry_type("") == "misc"


def test_bibtex_entry_to_bibtex():
    from litscribe.exporters.bibtex import BibTeXEntry
    entry = BibTeXEntry(
        entry_type="article",
        cite_key="smith2024test",
        fields={"title": "Test", "year": "2024"},
    )
    result = entry.to_bibtex()
    assert result.startswith("@article{smith2024test,")
    assert "title = {Test}" in result
    assert "year = {2024}" in result
    assert result.endswith("}")
